Repository wpmudev/shared-modules, pull requests merged in 2021-04, with the labels that each got.

#27 ✨ new(shared-presets): Create new package.
  packages/shared-configurations/dist/shared-configurations.cjs.js
  packages/shared-configurations/dist/shared-configurations.esm.js
  packages/shared-configurations/docs/shared-configurations.stories.js
  packages/shared-configurations/lib/shared-configurations.js
  packages/shared-configurations/package.json
  packages/shared-presets/LICENSE
  packages/shared-presets/README.md
  packages/shared-presets/__tests__/shared-configurations.test.js
  packages/shared-presets/dist/shared-presets.cjs.js
  packages/shared-presets/dist/shared-presets.esm.js
  packages/shared-presets/docs/images/hero-smush.png
  packages/shared-presets/docs/images/hero-smush@2x.png
  packages/shared-presets/docs/presets-page-free.stories.js
  packages/shared-presets/docs/presets-page-pro.stories.js
  packages/shared-presets/docs/presets-widget.stories.js
  packages/shared-presets/lib/components/accordion-item.js
  packages/shared-presets/lib/components/accordion.js
  packages/shared-presets/lib/components/table.js
  packages/shared-presets/lib/components/utils.js
  packages/shared-presets/lib/containers/shared-presets-page.js
  packages/shared-presets/lib/containers/shared-presets-widget.js
  packages/shared-presets/lib/shared-presets.js
  packages/shared-presets/package.json
  yarn.lock
Labels: new

#33 🐛 fix(react-presets): Add missing action callbacks to the widget component.
  packages/shared-presets/docs/presets-widget.stories.js
  packages/shared-presets/lib/containers/shared-presets-widget.js
Labels: bug

#34 🐛 fix(react-presets): Widget's buttons can't be translated.
  packages/shared-presets/docs/presets-widget.stories.js
  packages/shared-presets/lib/containers/shared-presets-widget.js
Labels: bug

#35 🐛 fix(module-presets): Make config items name match the key from the Hub.
  packages/shared-presets/docs/presets-page-free.stories.js
  packages/shared-presets/docs/presets-page-pro.stories.js
  packages/shared-presets/docs/presets-widget.stories.js
  packages/shared-presets/lib/components/accordion-item.js
  packages/shared-presets/lib/components/accordion.js
  packages/shared-presets/lib/containers/shared-presets-page.js
  packages/shared-presets/lib/containers/shared-presets-widget.js
Labels: improvement

#36 🐛 fix(shared-notifications-discount): Upgrade dependencies.
  packages/shared-notifications-discount/package.json
  yarn.lock
Labels: improvement

#37 🐛 fix(react-notifications-discount): Remove final asterisk from disclaimer text.
  packages/shared-notifications-discount/lib/shared-notifications-discount.js
Labels: bug

#38 🐛 fix(notifications-discount): Make price label and time editable.
  packages/shared-notifications-discount/docs/shared-notifications-discount.stories.js
  packages/shared-notifications-discount/lib/shared-notifications-discount.js
Labels: improvement

#39 📝 docs(notifications-discount): Installation instructions.
  packages/shared-notifications-discount/README.md
Labels: documentation

#40 🐛 fix(shared-presets): Upgrade dependencies.
  packages/shared-presets/package.json
  yarn.lock
Labels: improvement

#44 ✨ new(shared-presets): Add `loading` state.
  packages/shared-presets/docs/presets-page-free.stories.js
  packages/shared-presets/docs/presets-page-pro.stories.js
  packages/shared-presets/docs/presets-widget.stories.js
  packages/shared-presets/lib/containers/shared-presets-page.js
  packages/shared-presets/lib/containers/shared-presets-widget.js
Labels: new

#41 🐛 fix(shared-presets): Set red color for `delete` option.
  packages/shared-presets/lib/components/accordion-item.js
Labels: improvement

#45 🐛 fix(shared-presets): Remove unused state and convert to functional component
  packages/shared-presets/docs/presets-page-free.stories.js
  packages/shared-presets/docs/presets-page-pro.stories.js
  packages/shared-presets/lib/containers/shared-presets-page.js
  packages/shared-presets/lib/containers/shared-presets-widget.js
Labels: improvement

#46 🐛 fix(shared-presets): Updadate presets' property names to be more descriptive
  packages/shared-presets/docs/presets-page-free.stories.js
  packages/shared-presets/docs/presets-page-pro.stories.js
  packages/shared-presets/docs/presets-widget.stories.js
  packages/shared-presets/lib/containers/shared-presets-page.js
  packages/shared-presets/lib/containers/shared-presets-widget.js
Labels: improvement

#48 ✨ new(react-tutorials-list): Add `viewAll` link in the header.
  packages/react-tutorials-list/docs/react-tutorials-list.stories.js
  packages/react-tutorials-list/lib/react-tutorials-list.js
Labels: new

#50 🐛 fix(shared-presets): Upgrade `react-dropdown` dependency.
  packages/shared-presets/package.json
  yarn.lock
Labels: bug

#51 🐛 fix(shared-presets): Limit table text length to 2 lines.
  packages/shared-presets/lib/components/table.js
Labels: improvement

#52 🐛 fix(shared-tutorials-list): Properly style `viewAll` link.
  packages/react-tutorials-list/docs/react-tutorials-list.stories.js
  packages/react-tutorials-list/lib/react-tutorials-list.js
Labels: improvement

#53 🐛 fix(shared-notifications): Importing wrong file.
  packages/shared-notifications/lib/shared-notifications.js
Labels: bug
