Repository wpmudev/shared-modules, pull requests merged in 2022-02, with the labels that each got.

#107 docs(presets): Find a way to show presets on Storybook.
  packages/shared-presets/docs/demo-data.js
  packages/shared-presets/docs/shared-presets-page.stories.js
  packages/shared-presets/docs/shared-presets-widget.stories.js
  packages/shared-presets/lib/shared-presets.js
Labels: improvement

#112 fix(presets): Mobile view is broken.
  packages/shared-presets/lib/components/accordion-item.js
  packages/shared-presets/lib/components/utils.js
  packages/shared-presets/lib/shared-presets.js
Labels: bug

#108 fix(presets): Update edit icon button tooltip content.
  packages/shared-presets/lib/components/accordion-item.js
  packages/shared-presets/lib/shared-presets.js
Labels: improvement

#113 fix(presets): 404 console error when white label is turned on.
  packages/shared-presets/lib/components/accordion-item.js
Labels: bug

#116 fix(tutorials-slider): Upgrade `dependencies` to its latest versions.
  packages/shared-tutorials-slider/package.json
  yarn.lock
Labels: improvement

#118 Upgrade to Storybook 6.4.19.
  .eslintrc.json
  .storybook/main.js
  package.json
  yarn.lock
Labels: internal

#119 Upgrade global `dependencies` to its latest versions.
  .storybook/body-class.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: internal

#120 fix(presets): Remove unnecessary files when packing.
  packages/shared-presets/.npmignore
Labels: bug

#123 🔒️ codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: internal
