Repository wpmudev/shared-modules, pull requests merged in 2023-02, with the labels that each got.

#161 feat(header): External session component
  packages/shared-header/README.md
  packages/shared-header/docs/shared-header-demos.stories.js
  packages/shared-header/docs/shared-header-states.stories.js
  packages/shared-header/lib/components/session-external.js
  packages/shared-header/lib/shared-header.js
  packages/shared-header/package.json
Labels: new

#162 fix(header): Avatar not showing up
  packages/shared-header/lib/components/session-button.js
  packages/shared-header/lib/components/session-content.js
  packages/shared-header/lib/components/session-menu.js
  packages/shared-header/lib/components/session-on.js
Labels: bug

#164 fix(header): Update modal banner
  packages/shared-header/lib/images/upgrade-banner.png
  packages/shared-header/lib/images/upgrade-banner@2x.png
Labels: improvement

#163 feat(header): Create element to trigger modal outside header
  packages/shared-header/README.md
  packages/shared-header/docs/shared-header-demos.stories.js
  packages/shared-header/lib/components/session-external.js
Labels: new
