Repository wpmudev/shared-modules, pull requests merged in 2023-01, with the labels that each got.

#140 fix(presets): Use latest React modal component
  packages/shared-compiler/lib/shared-compiler.js
  packages/shared-presets/package.json
Labels: improvement

#138 docs(presets): Set demo data and add upload button functionality
  packages/shared-presets/docs/demo-data.js
  packages/shared-presets/lib/components/delete-modal.js
  packages/shared-presets/lib/shared-presets.js
Labels: documentation

#150 fix(presets): Correct shortened description text
  packages/shared-presets/lib/components/table.js
Labels: bug

#154 feat(header): Create new package
  .storybook/preview.js
  package.json
  packages/shared-header/README.md
  packages/shared-header/__tests__/shared-header.test.js
  packages/shared-header/docs/shared-header-demos.stories.js
  packages/shared-header/docs/shared-header-session.stories.js
  packages/shared-header/docs/shared-header-states.stories.js
  packages/shared-header/lib/components/session-button.js
  packages/shared-header/lib/components/session-content.js
  packages/shared-header/lib/components/session-list.js
  packages/shared-header/lib/components/session-menu.js
  packages/shared-header/lib/components/session-modal.js
  packages/shared-header/lib/components/session-off.js
  packages/shared-header/lib/components/session-on.js
  packages/shared-header/lib/components/utils.js
  packages/shared-header/lib/images/upgrade-banner.png
  packages/shared-header/lib/images/upgrade-banner@2x.png
  packages/shared-header/lib/shared-header.js
  packages/shared-header/package.json
  yarn.lock
Labels: new

#125 feat(presets): Add "Bulk Delete" ability
  packages/shared-presets/docs/demo-data.js
  packages/shared-presets/lib/components/accordion-item.js
  packages/shared-presets/lib/shared-presets.js
  packages/shared-presets/package.json
Labels: new

#136 feat(presets): Add pro tag in inactive features
  packages/shared-presets/lib/components/table.js
Labels: new

#156 fix(header): Use target icon for "Product Roadmap" link
  packages/shared-header/lib/components/session-menu.js
Labels: improvement

#157 fix(header): Update modal banner
  packages/shared-header/lib/images/upgrade-banner.png
  packages/shared-header/lib/images/upgrade-banner@2x.png
Labels: improvement

#158 fix(header): CSJ and ESM files are missing during built
  packages/shared-compiler/lib/shared-compiler.js
  packages/shared-header/dist/shared-header.cjs.js
  packages/shared-header/dist/shared-header.esm.js
  packages/shared-modules/dist/shared-modules.cjs.js
  packages/shared-modules/dist/shared-modules.esm.js
  packages/shared-presets/dist/shared-presets.cjs.js
  packages/shared-presets/dist/shared-presets.esm.js
Labels: bug

#159 fix(header): Update roadmap icon
  package.json
  packages/shared-header/lib/components/session-menu.js
  yarn.lock
Labels: improvement

#160 fix(header): Upsell menu link icon and label not editable
  packages/shared-header/lib/components/session-content.js
  packages/shared-header/lib/components/session-menu.js
  packages/shared-header/lib/components/session-on.js
  packages/shared-header/lib/components/utils.js
  packages/shared-header/lib/shared-header.js
Labels: bug
